# This file was generated by GoReleaser. DO NOT EDIT.
cask "emission" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "fe6536c55aaf884bd0cc17a6197e372f6673c7f6222ca7af5da20dbdf6c1e8ba"
      url "https://github.com/jdel/emission/releases/download/v#{version}/emission-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/jdel/emission/"
    end
    on_arm do
      sha256 "9fd6bf98a7d891c3932fe286dbb100acf8013d7ba38f888c212b953d0717b13a"
      url "https://github.com/jdel/emission/releases/download/v#{version}/emission-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/jdel/emission/"
    end
  end

  on_linux do
    on_intel do
      sha256 "6fa148d464e42da8ab38f6538942e38e0e9f4361dffb05398d4824eaa5fcb1f9"
      url "https://github.com/jdel/emission/releases/download/v#{version}/emission-#{version}-linux-amd64.tar.gz",
        verified: "github.com/jdel/emission/"
    end
    on_arm do
      sha256 "f0125ddc6dd66afdee1e32f43ccd8af5ae7f9dfe617e59b357947d8a77ded96c"
      url "https://github.com/jdel/emission/releases/download/v#{version}/emission-#{version}-linux-arm64.tar.gz",
        verified: "github.com/jdel/emission/"
    end
  end

  name "emission"
  desc "Spoof BitTorrent tracker announces to boost your ratio"
  homepage "https://github.com/jdel/emission"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "emission"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/emission"]
    end
  end

  # No zap stanza required

end
