# This file was generated by GoReleaser. DO NOT EDIT.
cask "emission" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "12aef7a1d60dcaa9216bb83fbf30a0899af8b835897e38b16467a024caf24279"
      url "https://github.com/jdel/emission/releases/download/v#{version}/emission-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/jdel/emission/"
    end
    on_arm do
      sha256 "2f561720e6e4d4699b1eb07197a41a2ff0d13591728070002d5897e2acd25f10"
      url "https://github.com/jdel/emission/releases/download/v#{version}/emission-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/jdel/emission/"
    end
  end

  on_linux do
    on_intel do
      sha256 "56cdbe753f1016a54548b9e4e6b467fd961656317b90001ec6632c6ddd85af4a"
      url "https://github.com/jdel/emission/releases/download/v#{version}/emission-#{version}-linux-amd64.tar.gz",
        verified: "github.com/jdel/emission/"
    end
    on_arm do
      sha256 "5d92cd919beb7b8efc0cc61593021166740607905739eb43b27aedfd78b57f96"
      url "https://github.com/jdel/emission/releases/download/v#{version}/emission-#{version}-linux-arm64.tar.gz",
        verified: "github.com/jdel/emission/"
    end
  end

  name "emission"
  desc "Spoof BitTorrent tracker announces to boost your ratio"
  homepage "https://github.com/jdel/emission"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "emission"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/emission"]
    end
  end

  zap trash: [
      "~/Library/Application Support/emission",
      "~/Library/Preferences/emission",
    ]

end
