# This file was generated by GoReleaser. DO NOT EDIT.
cask "emission" do
  version "0.3.3"

  on_macos do
    on_intel do
      sha256 "36aa5dcd794e2c1a968f1ade64c70bfb77affe5e5d14617b9443f05e148162f9"
      url "https://github.com/jdel/emission/releases/download/v#{version}/emission-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/jdel/emission/"
    end
    on_arm do
      sha256 "62461846bd0a54c55b109d8d3cc305990f926d13547431eb9bb1d319167eb1a5"
      url "https://github.com/jdel/emission/releases/download/v#{version}/emission-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/jdel/emission/"
    end
  end

  on_linux do
    on_intel do
      sha256 "270deef11ca9f13261b28a9e7169bebc50cf5ae9333be0fb060b8b57b75c063a"
      url "https://github.com/jdel/emission/releases/download/v#{version}/emission-#{version}-linux-amd64.tar.gz",
        verified: "github.com/jdel/emission/"
    end
    on_arm do
      sha256 "3d718baea52dc129adedc5417b02019f20c3d8d500dbb3f0b510f8d485e030f7"
      url "https://github.com/jdel/emission/releases/download/v#{version}/emission-#{version}-linux-arm64.tar.gz",
        verified: "github.com/jdel/emission/"
    end
  end

  name "emission"
  desc "Spoof BitTorrent tracker announces to boost your ratio"
  homepage "https://github.com/jdel/emission"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "emission"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/emission"]
    end
  end

  zap trash: [
      "~/Library/Application Support/emission",
      "~/Library/Preferences/emission",
    ]

end
