# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emission < Formula
  desc "Spoof BitTorrent tracker announces to boost your ratio"
  homepage "https://github.com/jdel/emission"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdel/emission/releases/download/v0.3.1/emission-0.3.1-darwin-amd64.tar.gz"
      sha256 "b952dadfdea1bd3d9dfd39446dcaf832c1915f1ba2c33995c8c4269df7cff464"

      define_method(:install) do
        bin.install "emission"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdel/emission/releases/download/v0.3.1/emission-0.3.1-darwin-arm64.tar.gz"
      sha256 "39c6e26b59a170322040d1e0ca304a9f78ce24256657794af864f822223674c8"

      define_method(:install) do
        bin.install "emission"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdel/emission/releases/download/v0.3.1/emission-0.3.1-linux-amd64.tar.gz"
      sha256 "56595983930888108a28059eab530b292811e04057fca6d9c59d096f940e8749"
      define_method(:install) do
        bin.install "emission"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdel/emission/releases/download/v0.3.1/emission-0.3.1-linux-arm64.tar.gz"
      sha256 "9d2d8f6b93826bca07504cdb498649664a97e47bf815df4f95536a55d39fc0aa"
      define_method(:install) do
        bin.install "emission"
      end
    end
  end

  test do
    system "#{bin}/emission --help"
  end
end
