# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emission < Formula
  desc "Spoof BitTorrent tracker announces to boost your ratio"
  homepage "https://github.com/jdel/emission"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdel/emission/releases/download/v0.2.0/emission-0.2.0-darwin-amd64.tar.gz"
      sha256 "6582d4e67037741ca13b9cbcbb1429c5a50522dbcac1c6d2174a62ace1c80ca6"

      define_method(:install) do
        bin.install "emission"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdel/emission/releases/download/v0.2.0/emission-0.2.0-darwin-arm64.tar.gz"
      sha256 "d2ab20f0f94d7d37042776cdea8b2407ec628467fb4980367c3956c41da0df2e"

      define_method(:install) do
        bin.install "emission"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdel/emission/releases/download/v0.2.0/emission-0.2.0-linux-amd64.tar.gz"
      sha256 "b1ef7416755bda0ea55f7e455526c03f160ff94cb7ab8378db20b164122bd381"
      define_method(:install) do
        bin.install "emission"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdel/emission/releases/download/v0.2.0/emission-0.2.0-linux-arm64.tar.gz"
      sha256 "492afc5b78c538d12e9c5840faeaa979306843f4d47ac8adaee965d15c9ca8bb"
      define_method(:install) do
        bin.install "emission"
      end
    end
  end

  test do
    system "#{bin}/emission --help"
  end
end
