# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slide < Formula
  desc "Slide CLI"
  homepage "https://github.com/jdel/slide"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdel/slide/releases/download/v0.0.2/slide-0.0.2-darwin-amd64.zip"
      sha256 "e970e7f4643882e7d11864a013fa941fc4316d327beee502525908f51f84f8d6"

      def install
        bin.install "slide"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdel/slide/releases/download/v0.0.2/slide-0.0.2-darwin-arm64.zip"
      sha256 "9f90eef98b718e756431b575fd0020ec13bdb9812a5943cc9bd057fc0c4e4e38"

      def install
        bin.install "slide"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/jdel/slide/releases/download/v0.0.2/slide-0.0.2-linux-amd64.zip"
      sha256 "4422f07bc79ebd2502fd6e2c9d33719fa7623a8138d93b163d8432c5e3c9816a"
      def install
        bin.install "slide"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/jdel/slide/releases/download/v0.0.2/slide-0.0.2-linux-arm6.zip"
      sha256 "41aa4096ffc863b1fee19bf844712ebd0b95d88e0e25cd11da3ea2e6639d1990"
      def install
        bin.install "slide"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/jdel/slide/releases/download/v0.0.2/slide-0.0.2-linux-arm64.zip"
      sha256 "ee46ce730cdb781ddb954e4ce18bc912fbe87497adebbd745d3b2bcfa30aacd7"
      def install
        bin.install "slide"
      end
    end
  end

  test do
    system "#{bin}/slide --version"
  end
end
