# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slide < Formula
  desc "Slide CLI"
  homepage "https://github.com/jdel/slide"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jdel/slide/releases/download/v0.0.5/slide-0.0.5-darwin-amd64.zip"
      sha256 "c161635608278741d1c3788d3614dfb46190f3102f3104f3e9f582e85cb13530"

      define_method(:install) do
        bin.install "slide"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jdel/slide/releases/download/v0.0.5/slide-0.0.5-darwin-arm64.zip"
      sha256 "61abc9a4984e54cb7cd47c14d61b75b7b7c2bcbb8ac9b6007527fca285c2ee57"

      define_method(:install) do
        bin.install "slide"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdel/slide/releases/download/v0.0.5/slide-0.0.5-linux-amd64.zip"
      sha256 "084ce9dc243d4005e6020e6eaa9a186d670367e5b57303d671123285178d1519"
      define_method(:install) do
        bin.install "slide"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jdel/slide/releases/download/v0.0.5/slide-0.0.5-linux-arm6.zip"
      sha256 "d1f9cf0f8568ab67bdde2cff7145354cfbac1fa2fa486069427381529ba326d9"
      define_method(:install) do
        bin.install "slide"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jdel/slide/releases/download/v0.0.5/slide-0.0.5-linux-arm64.zip"
      sha256 "39919497672daf5393d51a88c2c7b4d6eff16a86b8cd5ef00bc6088791c47450"
      define_method(:install) do
        bin.install "slide"
      end
    end
  end

  test do
    system "#{bin}/slide --version"
  end
end
